{% set name = "openseries" %}
{% set version = "1.4.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openseries-{{ version }}.tar.gz
  sha256: 921164879b719334049a8fa3e9da9f5d604c9a9ccc1221d4fa5f9c8dd78f97c9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - poetry-core
    - pip
  run:
    - python >=3.9,<3.13
    - ffn >=1.0.0,<2.0.0
    - holidays >=0.30,<1.0
    - numpy >=1.23.2,<=2.0.0
    - openpyxl >=3.1.2,<4.0.0
    - pandas >=2.1.2,<3.0.0
    - plotly >=5.18.0,<6.0.0
    - pyarrow >=14.0.2,<16.0.0
    - pydantic >=2.5.2,<3.0.0
    - python-dateutil >=2.8.2,<3.0.0
    - scipy >=1.11.4,<2.0.0
    - statsmodels >=0.14.0,<1.0.0

test:
  imports:
    - openseries
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CaptorAB/OpenSeries
  summary: Package for analyzing financial timeseries.
  license: BSD-3-Clause
  license_file: LICENSE.md
  doc_url: https://github.com/CaptorAB/OpenSeries
  dev_url: https://github.com/CaptorAB/OpenSeries

extra:
  recipe-maintainers:
    - karrmagadgeteer2
