{% set name = "openseries" %}
{% set version = "2.1.6" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openseries-{{ version }}.tar.gz
  sha256: 4b06f37819737de8f5d0ddf235f042bb8779c4aeb6995100c0fac83edd919d50

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=2.3.1
    - pip
    - numpy >=1.23.2
  run:
    - python >={{ python_min }}
    - exchange-calendars >=4.8
    - holidays >=0.30
    - numpy >=1.23.2
    - openpyxl >=3.1.2
    - pandas >=2.1.2
    - plotly >=5.18.0
    - pydantic >=2.5.2
    - python-dateutil >=2.8.2
    - requests >=2.20.0
    - scipy >=1.14.1
    - scikit-learn >=1.4.0
    - tzdata

test:
  imports:
    - openseries
  commands:
    - pip check
    - python -c "import openseries; print(openseries.__version__)"
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://captorab.github.io/openseries/
  summary: Tools to analyze financial timeseries.
  license: BSD-3-Clause
  license_file: LICENSE.md
  doc_url: https://openseries.readthedocs.io
  dev_url: https://github.com/CaptorAB/openseries
  description: |
    Tools to analyze financial timeseries of single assets or portfolios. It is made for daily or less frequent data.

extra:
  recipe-maintainers:
    - karrmagadgeteer2
