{% set name = "openseries" %}
{% set version = "1.7.8" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openseries-{{ version }}.tar.gz
  sha256: 734c44182d5999e817f8ed5e75887350e3be2b33cdeec48cae69d0f2b81d5c64

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=2.0.1
    - pip
    - numpy >=1.23.2,<3.0.0
  run:
    - python >={{ python_min }}
    - holidays >=0.30,<1.0
    - numpy >=1.23.2,<3.0.0
    - openpyxl >=3.1.2,<4.0.0
    - pandas >=2.1.2,<3.0.0
    - plotly >=5.18.0,<6.0.0
    - pyarrow >=14.0.2,<20.0.0
    - pydantic >=2.5.2,<3.0.0
    - python-dateutil >=2.8.2,<3.0.0
    - requests >=2.20.0,<3.0.0
    - scipy >=1.11.4,<2.0.0
    - statsmodels >=0.14.0,!=0.14.2,<1.0.0

test:
  imports:
    - openseries
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/CaptorAB/openseries
  summary: Tools for analyzing financial timeseries.
  license: BSD-3-Clause
  license_file: LICENSE.md
  doc_url: https://github.com/CaptorAB/openseries
  description: |
    openseries is a project with tools to analyze financial timeseries of a single asset or a group of assets.
    It is solely made for daily or less frequent data. Its origin is that our fund company needed basic tools
    to present historical performance to clients. Tools that can also be shared with clients for their own use.

extra:
  recipe-maintainers:
    - karrmagadgeteer2
